package com.rjnr.pocketnode.data.gateway

/**
 * Recorded bridge payloads, for tests that need the real wire shapes rather
 * than hand-written stand-ins.
 *
 * Most of these were pulled straight off the public CKB testnet JSON-RPC at
 * `https://testnet.ckb.dev/rpc` on 2026-09-15. That is the same
 * `ckb-jsonrpc-types` / `ckb-indexer` encoding the light client emits: the
 * bridge builds the very same structs (`service.rs`: `Cell`, `CellsCapacity`,
 * `Pagination`, `TxWithCell`, `ScriptStatus`, `FetchStatus`) and serializes
 * them with serde, so a payload recorded from a node decodes identically to one
 * recorded from the bridge.
 *
 * The four that no public endpoint can hand back in the bridge's exact shape
 * ([GET_TRANSACTIONS_PAGE], [GET_SCRIPTS], [LOCAL_NODE_INFO] and [GET_PEERS])
 * are assembled from real recorded values into the shape `service.rs` defines;
 * each says so and says what was changed. [FETCH_HEADER_ADDED],
 * [FETCH_HEADER_FETCHING], [FETCH_TRANSACTION_ADDED],
 * [FETCH_TRANSACTION_FETCHING], [CALL_RPC_NOT_INITIALIZED],
 * [EXTRACT_DAO_FIELDS] and [CALCULATE_UNLOCK_EPOCH] are likewise written to
 * the exact shapes `service.rs`, `bridge_core/rpc.rs` and `bridge_core/dao.rs`
 * emit, over real recorded inputs. Nothing here is invented: every hash,
 * capacity, cursor, epoch and block number came off the chain.
 *
 * One caveat on the two `last_cursor` values. They are real indexer cursors and
 * they are opaque bytes, but they are indexer-shaped, not light-client-shaped:
 * they lead with the node indexer's prefix byte (`0x40`, `0x80`) where the
 * light client's own store would lead with its `KeyPrefix` (`CellLockScript` =
 * 0x20, `TxLockScript` = 0x60, `storage/mod.rs`). Nothing decodes a cursor -
 * it is passed straight back to the bridge on the next page - so this does not
 * affect what the fixtures prove, and they are deliberately left as recorded
 * rather than regenerated by hand.
 *
 * Every constant must decode with the `@Serializable` models in
 * `data.gateway.models`. [LightClientApiFixtureTest] is what keeps that true.
 */
object LightClientFixtures {

    /**
     * `get_tip_header` -> `HeaderView`. Testnet block 22,431,838 (0x156445e),
     * recorded from `get_tip_header` on testnet.ckb.dev.
     */
    const val TIP_HEADER: String = """
        {
          "compact_target": "0x1d084699",
          "dao": "0x3e5c046cfccd7958bba518d3ad522a00c8898994125e570a004a7313a1ec7409",
          "epoch": "0x70805c5003608",
          "extra_hash": "0x6b54dbfb0868a94f146ad3736372684063881b3dab4c1525a59d1cfb704d2ab6",
          "hash": "0x7f1786c8b1b6a7ed8fbe96aaa41b1be4401cc63101e27797a7c3a15ba4561eba",
          "nonce": "0x45b0d45903558918c977b763f38cb639",
          "number": "0x156445e",
          "parent_hash": "0x036e5f9a486e846fc48481f66aeb352777d114ab62bd8fe27eeb3ab93ae74994",
          "proposals_hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "timestamp": "0x1a0a7349d41",
          "transactions_root": "0x99e173c06f29031d801655dae8e93060fa86a3706ff4ee28506a38af8929ec4e",
          "version": "0x0"
        }
    """

    /** Tip block number carried by [TIP_HEADER], for assertions. */
    const val TIP_HEADER_NUMBER: Long = 0x156445e

    /**
     * `get_header` -> `HeaderView` for testnet block 12 (0xc), the block that
     * committed [GET_TRANSACTION_COMMITTED]. Recorded from `get_header` on
     * testnet.ckb.dev.
     */
    const val HEADER_BLOCK_12: String = """
        {
          "compact_target": "0x1e015555",
          "dao": "0x343d33782f21a12e7fe864f2f2862300b9e94907a0000000004f4b0b04fbfe06",
          "epoch": "0x3e8000c000000",
          "extra_hash": "0xad22239f5cf73ca4a75261ac3ea96169e8543226b143205d0f6987a26c8aa39b",
          "hash": "0xfb27201670e48f65b93b58c4cac7348c54554ad831ed5c1b386c9bd3c24fa911",
          "nonce": "0x50e30c2a3df9de17fd0d1abb3b5e9206",
          "number": "0xc",
          "parent_hash": "0x18b8cda2aecd83b25df917e28fde1bff31f032085463dd805074df0e68edeec6",
          "proposals_hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "timestamp": "0x1723b9a0f32",
          "transactions_root": "0x556ef527219d99eaf3909a715facd3579e3afb8a50f79e00bc58ecff0da1b847",
          "version": "0x0"
        }
    """

    /**
     * `fetch_header` -> `FetchStatus<HeaderView>`, Fetched arm. The envelope is
     * `#[serde(tag = "status", rename_all = "snake_case")]` per `service.rs`;
     * the payload is [HEADER_BLOCK_12] as recorded.
     */
    val FETCH_HEADER_FETCHED: String = """
        {
          "status": "fetched",
          "data": $HEADER_BLOCK_12
        }
    """

    /** `fetch_header` -> `FetchStatus<HeaderView>`, NotFound arm (a unit variant, so no payload). */
    const val FETCH_HEADER_NOT_FOUND: String = """{"status":"not_found"}"""

    /**
     * `fetch_header` -> `FetchStatus<HeaderView>`, Added arm: the fetch has
     * just been queued. `service.rs` declares the arm as
     * `Added { timestamp: Uint64 }` under `#[serde(tag = "status",
     * rename_all = "snake_case")]`, so the payload is a single hex millisecond
     * timestamp beside the tag. The value is testnet block 12's real
     * `timestamp`.
     */
    const val FETCH_HEADER_ADDED: String = """{"status":"added","timestamp":"0x1723b9a0f32"}"""

    /**
     * `fetch_header` -> `FetchStatus<HeaderView>`, Fetching arm: the request is
     * in flight, `first_sent` being when it first went out. This is the arm
     * callers retry on with backoff.
     */
    const val FETCH_HEADER_FETCHING: String =
        """{"status":"fetching","first_sent":"0x1723b9a0f32"}"""

    /** `fetch_transaction` -> `FetchStatus<TransactionWithStatus>`, Added arm. */
    const val FETCH_TRANSACTION_ADDED: String =
        """{"status":"added","timestamp":"0x1a0a7349d41"}"""

    /** `fetch_transaction` -> `FetchStatus<TransactionWithStatus>`, Fetching arm. */
    const val FETCH_TRANSACTION_FETCHING: String =
        """{"status":"fetching","first_sent":"0x1a0a7349d41"}"""

    /**
     * `get_cells` -> `Pagination<Cell>`, two cells on the testnet
     * secp256k1-blake160 lock `0xda6484...0ef0e1`, ascending, limit 2.
     * Recorded from `get_cells` on testnet.ckb.dev; `last_cursor` is the
     * indexer's real cursor for that page.
     */
    const val GET_CELLS_PAGE: String = """
        {
          "last_cursor": "0x409bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce801da648442dbb7347e467d1d09da13e5cd3a0ef0e10000000000005fa60000000000000000",
          "objects": [
            {
              "block_number": "0x5fa5",
              "out_point": {
                "index": "0x0",
                "tx_hash": "0x68b6cabb75821b0e316bda61f5b8fe5555215b637db29d3bab6ca7f42714db57"
              },
              "output": {
                "capacity": "0x374f10a5f2",
                "lock": {
                  "args": "0xda648442dbb7347e467d1d09da13e5cd3a0ef0e1",
                  "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                  "hash_type": "type"
                },
                "type": null
              },
              "output_data": "0x",
              "tx_index": "0x0"
            },
            {
              "block_number": "0x5fa6",
              "out_point": {
                "index": "0x0",
                "tx_hash": "0xcfe64b1cd6ac96e4a5daf295a6d395cc6f237df47212515086c22e76a8e2dbbf"
              },
              "output": {
                "capacity": "0x7c4e4e2fb1",
                "lock": {
                  "args": "0xda648442dbb7347e467d1d09da13e5cd3a0ef0e1",
                  "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                  "hash_type": "type"
                },
                "type": null
              },
              "output_data": "0x",
              "tx_index": "0x0"
            }
          ]
        }
    """

    /** Capacity of the first cell in [GET_CELLS_PAGE], for assertions. */
    const val GET_CELLS_FIRST_CAPACITY: Long = 0x374f10a5f2

    /**
     * `get_transactions` -> `Pagination<Tx>`, one ungrouped `TxWithCell`.
     *
     * Assembled, because no public endpoint returns this shape: a full node's
     * indexer answers `get_transactions` with the short ungrouped form
     * (`tx_hash` only), while the light client answers with `TxWithCell`
     * (`service.rs`), which inlines the whole `TransactionView` and adds
     * `io_capacity`. Every value is real: the envelope fields
     * (`block_number` 0xc, `tx_index` 0x0, `io_index` 0x0, `io_type`
     * "output") and `last_cursor` are the testnet indexer's own answer for
     * lock `0xda6484...0ef0e1`, `transaction` is
     * [GET_TRANSACTION_COMMITTED]'s transaction as recorded, and
     * `io_capacity` is that output's capacity.
     */
    const val GET_TRANSACTIONS_PAGE: String = """
        {
          "last_cursor": "0x809bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce801da648442dbb7347e467d1d09da13e5cd3a0ef0e1000000000000000c000000000000000001",
          "objects": [
            {
              "transaction": {
                "cell_deps": [],
                "hash": "0xa6789f42b0568b1872e5a5858f0c42148dd8d313f844252f5fe3dfe556958ba9",
                "header_deps": [],
                "inputs": [
                  {
                    "previous_output": {
                      "index": "0xffffffff",
                      "tx_hash": "0x0000000000000000000000000000000000000000000000000000000000000000"
                    },
                    "since": "0xc"
                  }
                ],
                "outputs": [
                  {
                    "capacity": "0x2ecbd7f365",
                    "lock": {
                      "args": "0xda648442dbb7347e467d1d09da13e5cd3a0ef0e1",
                      "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                      "hash_type": "type"
                    },
                    "type": null
                  }
                ],
                "outputs_data": ["0x"],
                "version": "0x0",
                "witnesses": [
                  "0x5d0000000c00000055000000490000001000000030000000310000009bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce80114000000da648442dbb7347e467d1d09da13e5cd3a0ef0e104000000deadbeef"
                ]
              },
              "block_number": "0xc",
              "tx_index": "0x0",
              "io_index": "0x0",
              "io_type": "output",
              "io_capacity": "0x2ecbd7f365"
            }
          ]
        }
    """

    /**
     * `get_transaction` -> `TransactionWithStatus`, committed. Recorded from
     * `get_transaction` on testnet.ckb.dev for the cellbase of testnet block 12.
     *
     * Trimmed to the bridge's shape. A full node answers with more than the
     * light client does: `fee`, `min_replace_fee` and `time_added_to_pool` at
     * the top level, and `block_number`, `reason` and `tx_index` inside
     * `tx_status`. `service.rs` defines `TransactionWithStatus` as exactly
     * `transaction` + `cycles` + `tx_status`, and `TxStatus` as exactly
     * `status` + `block_hash`, so those keys are dropped here rather than left
     * in for `ignoreUnknownKeys` to absorb.
     */
    const val GET_TRANSACTION_COMMITTED: String = """
        {
          "cycles": null,
          "transaction": {
            "cell_deps": [],
            "hash": "0xa6789f42b0568b1872e5a5858f0c42148dd8d313f844252f5fe3dfe556958ba9",
            "header_deps": [],
            "inputs": [
              {
                "previous_output": {
                  "index": "0xffffffff",
                  "tx_hash": "0x0000000000000000000000000000000000000000000000000000000000000000"
                },
                "since": "0xc"
              }
            ],
            "outputs": [
              {
                "capacity": "0x2ecbd7f365",
                "lock": {
                  "args": "0xda648442dbb7347e467d1d09da13e5cd3a0ef0e1",
                  "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                  "hash_type": "type"
                },
                "type": null
              }
            ],
            "outputs_data": ["0x"],
            "version": "0x0",
            "witnesses": [
              "0x5d0000000c00000055000000490000001000000030000000310000009bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce80114000000da648442dbb7347e467d1d09da13e5cd3a0ef0e104000000deadbeef"
            ]
          },
          "tx_status": {
            "status": "committed",
            "block_hash": "0xfb27201670e48f65b93b58c4cac7348c54554ad831ed5c1b386c9bd3c24fa911"
          }
        }
    """

    /**
     * `get_cells_capacity` -> `CellsCapacity` for the testnet lock
     * `0xa89782...afad7`. Recorded from `get_cells_capacity` on
     * testnet.ckb.dev; the block hash and number are the tip the indexer
     * answered against.
     */
    const val CELLS_CAPACITY: String = """
        {
          "block_hash": "0x80d9c118309adb9622f564d2b3aad2245f75fe43d5ac8fa6ff5b33decbd1e943",
          "block_number": "0x156445c",
          "capacity": "0x14f33c9aef2b"
        }
    """

    /** Capacity carried by [CELLS_CAPACITY], in shannons. */
    const val CELLS_CAPACITY_SHANNONS: Long = 0x14f33c9aef2b

    /**
     * `local_node_info` -> `LocalNode`. Recorded from `local_node_info` on
     * testnet.ckb.dev; `addresses` and `protocols` are emptied and `version`
     * replaced with the light-client crate version, because
     * `bridge_core::query::local_node_info` builds the struct itself with
     * `addresses: vec![]`, `protocols: vec![]` and `env!("CARGO_PKG_VERSION")`
     * (its two TODOs). `node_id` and `connections` are the real recorded
     * values.
     */
    const val LOCAL_NODE_INFO: String = """
        {
          "active": true,
          "addresses": [],
          "connections": "0x8",
          "node_id": "QmWQA9KpXekAmpkLsUBBKM6fHWuX5dVrDzmcmr9TuKmWiG",
          "protocols": [],
          "version": "0.5.4"
        }
    """

    /**
     * `get_peers` -> `[RemoteNode]`. The three peers are real, recorded from
     * `get_peers` on testnet.ckb.dev (client version, node id and the hex
     * `connected_duration`); `addresses`, `protocols` and `sync_state` are
     * emptied or nulled to match what `bridge_core::query::get_peers` emits.
     */
    const val GET_PEERS: String = """
        [
          {
            "addresses": [],
            "connected_duration": "0x871e06f",
            "node_id": "QmPcJY2gZLUm66szYA9QaG1P3rzwseWCMgbj6AyNCyW4G2",
            "protocols": [],
            "sync_state": null,
            "version": "0.209.0 (d166e28 2026-07-29)"
          },
          {
            "addresses": [],
            "connected_duration": "0x12fe3a19",
            "node_id": "QmfUTZxsse7rFJTJfoUv8bbStoDLETxst5nJEpJozNuAnH",
            "protocols": [],
            "sync_state": null,
            "version": "0.209.0 (d166e28 2026-07-29)"
          },
          {
            "addresses": [],
            "connected_duration": "0x17fe96a7",
            "node_id": "QmXz6zNTVxZCrWi1HWsyaVvCoBh8e8YrMFsdfnTD9JZNZn",
            "protocols": [],
            "sync_state": null,
            "version": "0.209.0 (d166e28 2026-07-29)"
          }
        ]
    """

    /**
     * `get_scripts` -> `[ScriptStatus]` for one registered lock. Assembled in
     * the shape `service.rs` defines (`script`, `script_type`,
     * `block_number`), because only a running light client answers this call.
     * The script is the real testnet secp256k1-blake160 lock used by
     * [GET_CELLS_PAGE] and the block number is the block that page's first
     * cell landed in.
     */
    const val GET_SCRIPTS: String = """
        [
          {
            "script": {
              "args": "0xda648442dbb7347e467d1d09da13e5cd3a0ef0e1",
              "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
              "hash_type": "type"
            },
            "script_type": "lock",
            "block_number": "0x5fa5"
          }
        ]
    """

    /**
     * `call_rpc` on a node that has not been initialized.
     *
     * The one query that reports failure in-band: `bridge_core/rpc.rs` returns
     * this envelope as a successful `String`, so the caller gets a non-null
     * answer carrying a JSON-RPC `error` rather than the null every other query
     * would give. Built from `rpc_error_response(-32603, "Light client not
     * initialized")`, whose `json!` literal fixes both the field order and the
     * hardcoded `"id": 1`. An unknown method takes the same shape with code
     * -32601.
     */
    const val CALL_RPC_NOT_INITIALIZED: String =
        """{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Light client not initialized"}}"""

    /**
     * `extract_dao_fields` for testnet block 12's `dao` field (the one in
     * [HEADER_BLOCK_12]).
     *
     * `bridge_core/dao.rs` splits the 32 bytes into four little-endian u64s and
     * formats them with `format!("0x{:x}")`, so the values are unpadded
     * lowercase hex, not the fixed-width hex the chain uses elsewhere.
     */
    const val EXTRACT_DAO_FIELDS: String =
        """{"c":"0x2ea1212f78333d34","ar":"0x2386f2f264e87f","s":"0xa00749e9b9","u":"0x6fefb040b4b4f00"}"""

    /**
     * `calculate_unlock_epoch` for a deposit in testnet epoch
     * `0x3e8000c000000` ([HEADER_BLOCK_12]) withdrawn in `0x70805c5003608`
     * ([TIP_HEADER]).
     *
     * Not JSON: `bridge_core/dao.rs` returns a bare `format!("0x{:x}")` of the
     * since value. The top byte is the absolute-epoch flag (`0x20`), and the
     * fraction carries the deposit epoch's own index and length rather than
     * 0/1, which is the #315 fix.
     */
    const val CALCULATE_UNLOCK_EPOCH: String = "0x2003e8000c003624"

    /** The absolute-epoch `since` flag the bridge ORs into [CALCULATE_UNLOCK_EPOCH]. */
    const val SINCE_ABSOLUTE_EPOCH_FLAG: Long = 0x2000000000000000
}
