import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'

export const metadata = {
  title: 'Privacy Policy — Pocket Node',
  description: 'Privacy Policy for Pocket Node CKB Light Wallet.',
}

/**
 * Privacy Policy page. Content is text-only and stable across releases,
 * so the page is server-rendered and statically generated. Long-form
 * reading mode: narrow single-column with the same Doto display +
 * Inter body type system as the rest of the site.
 *
 * Substance was ported from the legacy website/privacy.html. The
 * "Last updated" date moves forward whenever the policy text is
 * meaningfully changed; minor copyedits do not require a bump.
 */
export default function PrivacyPage() {
  return (
    <>
      <Navbar />

      <header className="border-b border-green/20 bg-bg">
        <div className="mx-auto max-w-content px-6 py-12 md:py-16">
          <p className="mb-4 font-doto text-xs font-black uppercase tracking-widest text-green">
            Legal
          </p>
          <h1 className="font-doto text-4xl font-bold uppercase leading-tight tracking-tight text-green md:text-6xl">
            Privacy Policy
          </h1>
          <p className="mt-4 font-doto text-sm font-semibold uppercase tracking-wide text-white/60">
            Last updated: 2026-05-21
          </p>
        </div>
      </header>

      <article className="mx-auto max-w-content px-6 py-12 md:py-16">
        <Section title="Introduction">
          <p>
            Pocket Node (&quot;the App&quot;) is a self-custody cryptocurrency
            wallet for the Nervos CKB blockchain. The App is designed with
            privacy as a core principle: it runs an embedded light client
            directly on your Android device and does not communicate with any
            servers operated by us.
          </p>
          <p>
            This Privacy Policy explains what data the App handles, how it is
            stored, and what permissions it requires. The short version: we
            collect nothing, store everything locally, and give you full
            control over your data.
          </p>
        </Section>

        <Section title="Data we collect">
          <p>
            <strong>None.</strong> Pocket Node does not collect, transmit, or
            store any personal data on external servers. Specifically:
          </p>
          <ul>
            <li>No account creation or registration is required</li>
            <li>No email addresses, names, or contact information is collected</li>
            <li>No analytics, telemetry, or usage tracking of any kind</li>
            <li>No crash reporting to external services</li>
            <li>No advertising identifiers or device fingerprinting</li>
            <li>No IP address logging by any server we operate (we operate no servers)</li>
          </ul>
        </Section>

        <Section title="Data stored on your device">
          <p>
            All data generated by the App is stored locally on your Android
            device. Nothing leaves your phone unless you explicitly initiate
            a blockchain transaction.
          </p>
        </Section>

        <Section title="Network communications">
          <p>
            The App communicates only with the decentralized Nervos CKB
            peer-to-peer network via the embedded light client. This is
            necessary to:
          </p>
          <ul>
            <li>Sync block headers and verify transactions</li>
            <li>Query cell (UTXO) data to determine your balance</li>
            <li>Broadcast signed transactions when you send CKB</li>
          </ul>
          <p>
            These connections are made directly to CKB network nodes, not to
            any server operated by us. The information exchanged is limited
            to blockchain protocol data (block headers, cell data, transaction
            data). Your IP address may be visible to CKB network peers, as is
            standard for any peer-to-peer blockchain client.
          </p>
        </Section>

        <Section title="Permissions">
          <p>Pocket Node requests the following Android permissions:</p>
          <ul>
            <li>
              <strong>Internet:</strong> required for the embedded light client
              to connect to CKB peers.
            </li>
            <li>
              <strong>Camera (optional):</strong> only when you use the in-app
              QR code scanner. Camera images are processed locally using an
              on-device barcode scanner. No images are stored or transmitted.
            </li>
            <li>
              <strong>Biometric:</strong> if you opt in, the system biometric
              prompt is used to unlock the wallet. Biometric data never leaves
              the device&#39;s secure hardware.
            </li>
          </ul>
        </Section>

        <Section title="Data deletion">
          <p>You have full control over your data at all times:</p>
          <ul>
            <li>
              <strong>Wipe wallet:</strong> use the in-app &quot;Delete
              Wallet&quot; option in Settings to erase all keys, preferences,
              and light client data from your device.
            </li>
            <li>
              <strong>Uninstall:</strong> uninstalling the App removes all
              locally stored data, including keys and blockchain data.
            </li>
            <li>
              <strong>No remote data:</strong> since no data is stored on our
              servers, there is nothing to request deletion of externally.
            </li>
          </ul>
          <p>
            <strong>Important:</strong> before deleting your wallet, ensure
            you have backed up your 12-word recovery phrase. Once deleted,
            your wallet can only be recovered using this phrase.
          </p>
        </Section>

        <Section title="Children's privacy">
          <p>
            Pocket Node is a financial application intended for users aged 18
            and older. We do not knowingly target or collect data from
            children under 18. The App does not collect data from any user
            regardless of age.
          </p>
        </Section>

        <Section title="Third-party services">
          <p>
            Pocket Node does not integrate any third-party analytics,
            advertising, or tracking services. The App does not use:
          </p>
          <ul>
            <li>Google Analytics or Firebase Analytics</li>
            <li>Crash reporting services (Crashlytics, Sentry, etc.)</li>
            <li>Advertising SDKs</li>
            <li>Social media SDKs</li>
          </ul>
          <p>
            The only external network communication is with the decentralized
            CKB peer-to-peer network, which is a core requirement for the
            wallet to function.
          </p>
        </Section>

        <Section title="Open source">
          <p>
            Pocket Node is fully open source. You can audit the complete
            source code, including all network communications, data storage,
            and cryptographic operations, on our{' '}
            <a href="https://github.com/RaheemJnr/pocket-node">
              GitHub repository
            </a>
            .
          </p>
        </Section>

        <Section title="Changes to this policy">
          <p>
            If we make changes to this Privacy Policy, we will update the
            &quot;Last updated&quot; date at the top of this page. Since the
            App collects no data, material changes are unlikely. Any changes
            will be reflected in the App&#39;s next release.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            If you have any questions about this Privacy Policy or the App,
            you can reach us through:
          </p>
          <ul>
            <li>
              GitHub Issues:{' '}
              <a href="https://github.com/RaheemJnr/pocket-node/issues">
                github.com/RaheemJnr/pocket-node/issues
              </a>
            </li>
            <li>GitHub Discussions on the repository</li>
          </ul>
        </Section>
      </article>

      <Footer />
    </>
  )
}

function Section({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) {
  return (
    <section className="mb-12">
      <h2 className="mb-4 font-doto text-2xl font-bold uppercase tracking-tight text-green md:text-3xl">
        {title}
      </h2>
      <div className="flex flex-col gap-4 font-sans text-base leading-relaxed text-white/85 [&_a]:text-green [&_a:hover]:underline [&_li]:list-disc [&_li]:ml-6 [&_strong]:text-white [&_ul]:flex [&_ul]:flex-col [&_ul]:gap-2">
        {children}
      </div>
    </section>
  )
}
