#!/usr/bin/env node
/**
 * Sync user-facing markdown from docs/ into website/content/ so the
 * /guide route can read from a path that lives under the website
 * project root.
 *
 * Canonical source remains docs/USER_GUIDE.md. The committed copy at
 * content/user-guide.md is regenerated by this script and serves two
 * roles: it lets Vercel build without needing parent-directory access,
 * and it gives reviewers a visible record of what shipped to the site.
 *
 * Run this whenever you edit the canonical guide. npm run prebuild
 * also invokes it automatically, so a clean `npm run build` always
 * picks up the latest source.
 */
import { copyFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const websiteRoot = resolve(__dirname, '..')
const repoRoot = resolve(websiteRoot, '..')

const sources = [
  {
    from: join(repoRoot, 'docs', 'USER_GUIDE.md'),
    to: join(websiteRoot, 'content', 'user-guide.md'),
  },
]

for (const { from, to } of sources) {
  if (!existsSync(from)) {
    // Soft-fail: if the canonical source isn't accessible (e.g. Vercel
    // running with a restricted root), the previously committed copy
    // under content/ is used as-is.
    console.warn(`[sync-content] source missing: ${from} — keeping committed copy`)
    continue
  }
  mkdirSync(dirname(to), { recursive: true })
  copyFileSync(from, to)
  console.log(`[sync-content] ${from} → ${to}`)
}
